name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
env:
  var1: abc
  var2: xyz

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Inject Variables
        uses: lindluni/actions-variable-groups@v2.1.2
        with:
          org: samsmithnz
          repo: VariablesYAMLTest
          #token: ${{ secrets.PAT }} #secrets.PAT is a PAT Token with content:read permission
          groups: |
            Variables/var1.yml
            var2.yml
      - name: Print Environment variables
        run: env | sort
